name: Go Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write  # Grant write permission to contents (for creating releases)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"

      - name: Build binaries
        run: |
          mkdir -p bin
          go mod tidy
          # Build for Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -o bin/hermes-linux-amd64 .
          # Build for macOS (arm64)
          GOOS=darwin GOARCH=arm64 go build -o bin/hermes-darwin-arm64 .
          # Build for Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -o bin/hermes-windows-amd64.exe .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Hermes Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hermes-linux-amd64
          asset_name: hermes-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Hermes Darwin Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hermes-darwin-arm64
          asset_name: hermes-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Hermes Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hermes-windows-amd64.exe
          asset_name: hermes-windows-amd64.exe
          asset_content_type: application/octet-stream
