name: Go Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # Grant write permission to contents (for creating releases)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o bin/myapp-linux-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bin/myapp-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -o bin/myapp-windows-amd64.exe .

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/*
          asset_name: ${{ github.ref_name }}-${{ runner.os }}-binary
          asset_content_type: ''
